### PR TITLE
Added several extra colors

### PR DESCRIPTION
**Pull request by ForeignSasquatch**

### CODE REVIEW

**Comment by jeremyfa** [comment]
Sorry, I still can’t merge this because you also commited other files that are unrelated (even an image file). Please make another pull request with only the changes in Color.hx.

Also noticed a typo (ORAGNERED instead of ORANGERED)

**Comment by jeremyfa** [comment]
Also DARKOLIVEGREEEN (with 3 E 😅)

not a bad idea to double check the names

**Comment by ForeignSasquatch** [comment]
> Sorry, I still can’t merge this because you also commited other files that are unrelated (even an image file). Please make another pull request with only the changes in Color.hx.
> 
> Also noticed a typo (ORAGNERED instead of ORANGERED)

that image was the one in the test image which i unknowingly renamed it was just renamed again

**Comment by ForeignSasquatch** [comment]
Fixed the typo

**Comment by jeremyfa** [comment]
Still can't merge it, because the history includes unrelated commits. To make it clean, you should fork a new branch from the official ceramic and only put the Color.hx changes.

If you are uncomfortable doing that on your machine, it's actually pretty easy to do it via Github directly:
- Go to the Color.hx page on the main ceramic-engine repository: https://github.com/ceramic-engine/ceramic/blob/master/runtime/src/ceramic/Color.hx
- Click on the pencil icon to edit the file
- Put your changes to Color.hx
- Save the change and submit the pull request automatically created for you.

I'm closing this current pull request because I won't be able to merge it, but waiting for your clean pull request following the above steps :)

**Comment by ForeignSasquatch** [comment]
👍

**Pull request closed without merging**
